"""add occupancy and hours to rec center room

Revision ID: 35d3b8eddb71
Revises: dae14a0af46f
Create Date: 2026-04-24 15:40:39.821846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d3b8eddb71'
down_revision = 'dae14a0af46f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rec_center_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('current_occupancy', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('opening_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('closing_time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rec_center_room', schema=None) as batch_op:
        batch_op.drop_column('closing_time')
        batch_op.drop_column('opening_time')
        batch_op.drop_column('current_occupancy')
        batch_op.drop_column('capacity')

    # ### end Alembic commands ###
